### ISSUE TITLE
[12.0] Branch for version 12.0 needed

### ISSUE THREAD

**Issue by marylla** [OCA/vertical-rental#2]
Hi there,
unfortunately I cannot create a pull request or push our vertical-rental code because we currently only have a branch for version 14 and 15 in this repo, but we can only provide the code in version 12 at the moment. I actually should maintain this repo as said here:
https://odoo-community.org/psc-teams/vertical-rental-187 but it seems I have not the correct access rights.

@pedrobaeza Can you create a 12.0 branch, give me write access to this repo or can you give me a link to any documentation describing what I should have done instead? Thanks a lot. :)

**Comment by pedrobaeza** [comment]
Created.
